"""add status to Trial

Revision ID: 7b2a29459460
Revises: 93391b3fd702
Create Date: 2025-12-04 11:04:57.614382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2a29459460'
down_revision: Union[str, Sequence[str], None] = '93391b3fd702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'status')
    # ### end Alembic commands ###
